### Changes are required ###

# Rclone remotes
[remote]
downloadSource = ["source1:", "source2:", "source3:"]
uploadDestination = ["destination1:", "destination2:", "destination3:"]
plex = "plex:" # <= This is not essential for the core functionalities of Shiden. Can be omitted.

############################################

### Changes are optional ###

# For notification module
[webhook]
discordWebhooks = [
  "https://discordapp.com/...",
  "https://discordapp.com/...",
  "https://discordapp.com/..."
]

# To display Shiden's status in a Discord bot's activity
[discord_bot]
token = ""

# Flags when running child processes
[flags]
rclone = "--progress --stats-one-line --stats 1s --bwlimit 20M -v --config conf/rclone.conf"

# List of preferred languages when choosing subtitle stream. Order MATTERS.
[subtitle]
language = ["eng", "en", "jpn", "jp"]

# ExpressJS settings
[express]
port = 64000
